<nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
    <div class="navbar-multiline mr-auto">
        <span class="navbar-brand" href="#0">Contacts</span>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Contacts</li>
            </ol>
        </nav>
    </div>
</nav>

<div class="container p-3">
    <div class="row">
        <div class="col-md-3">
            <div class="card mb-3">
                <div class="card-body">
                    <div>Total item: <?= number_format($total); ?></div>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <?php if($contacts): ?>
                <?php $csrf = $form->csrfToken(); ?>
                <ul class="list-group list-group-flush card mb-3">
                    <?php foreach($contacts as $contact): ?>
                        <?php $seen = $contact->seen && !is_null($contact->seen->time); ?>
                        <li class="list-group-item<?= ($seen?' list-group-item-seen':'') ?>">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">
                                    <?= $contact->subject->safe->chars(50) ?>...
                                </h5>
                                <div>
                                    <?php if($contact->user): ?>
                                        <i class="fas fa-reply" title="Replied"></i>
                                    <?php endif; ?>
                                    <div class="btn-group btn-group-sm" role="group" aria-label="Action">
                                        <a href="<?= $this->router->to('adminContactReply', ['id'=>$contact->id]) ?>" class="btn btn-secondary" title="Details">
                                            <i class="fas fa-info-circle"></i>
                                        </a>
                                        <div class="btn-group btn-group-sm" role="group">
                                            <button id="contact-action-<?= $contact->id ?>" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                                            <div class="dropdown-menu" aria-labelledby="contact-action-<?= $contact->id ?>">
                                                <a class="dropdown-item"
                                                    data-toggle="confirm"
                                                    data-text="Are you sure want to remove this item?"
                                                    data-btn-type="danger"
                                                    href="<?= $this->router->to('adminContactRemove', ['id'=>$contact->id], ['noob'=>$csrf]) ?>">Delete</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <small>
                                <span title="Created">
                                    <i class="far fa-calendar-plus"></i>
                                    <?= $contact->created->format('M d, Y H:i') ?>
                                </span>
                                &middot;
                                <span title="By">
                                    <i class="fas fa-user"></i>
                                    <?= $contact->fullname->safe ?> ( <?= $contact->email->safe ?> )
                                </span>
                            </small>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <?php if($pages): ?>
                <?= $this->partial('shared/pagination', ['pages'=>$pages, 'align'=>'right']); ?>
            <?php endif; ?>
        </div>
    </div>
</div>

<style>
    .list-group-item-seen{ background-color: rgba(214,216,219,.3); }
</style>
